### ISSUE TITLE
wrong date

### ISSUE THREAD

**Issue by e154** [sixdouglas/suncalc#4]
input parameters

current time:
2020-05-17 15:05:16.414278 +0700 +07 m=+2.439547175

position:
lat: 55.00737904819233
lon: 82.95613288879396

Sun pos azimuth(218.097705), elevation(49.632049)

function called
`times := suncalc.GetTimes(now, e.lat, e.lon)`

result:
{
   "dawn": {
     "MorningName": "dawn",
     "Time": "2020-05-17T04:29:45.597476352+07:00"
   },
   "dusk": {
     "MorningName": "dusk",
     "Time": "2020-05-17T22:22:12.176962304+07:00"
   },
   "goldenHour": {
     "MorningName": "goldenHour",
     "Time": "2020-05-17T20:37:57.783930368+07:00"
   },
   "goldenHourEnd": {
     "MorningName": "goldenHourEnd",
     "Time": "2020-05-17T06:13:59.990508544+07:00"
   },
   "nadir": {
     "MorningName": "nadir",
     "Time": "2020-05-17T01:25:58.887219456+07:00"
   },
   "nauticalDawn": {
     "MorningName": "nauticalDawn",
     "Time": "2020-05-17T03:16:15.785467136+07:00"
   },
   "nauticalDusk": {
     "MorningName": "nauticalDusk",
     "Time": "2020-05-17T23:35:41.988972032+07:00"
   },
   "night": {
     "MorningName": "night",
     "Time": "1677-09-21T05:44:23.145224192+05:31"
   },
   "nightEnd": {
     "MorningName": "nightEnd",
     "Time": "1677-09-21T05:44:23.145224192+05:31"
   },
   "solarNoon": {
     "MorningName": "solarNoon",
     "Time": "2020-05-17T13:25:58.887219456+07:00"
   },
   "sunrise": {
     "MorningName": "sunrise",
     "Time": "2020-05-17T05:18:13.48675328+07:00"
   },
   "sunriseEnd": {
     "MorningName": "sunriseEnd",
     "Time": "2020-05-17T05:22:50.375977472+07:00"
   },
   "sunset": {
     "MorningName": "sunset",
     "Time": "2020-05-17T21:33:44.287685888+07:00"
   },
   "sunsetStart": {
     "MorningName": "sunsetStart",
     "Time": "2020-05-17T21:29:07.39846144+07:00"
   }
 }

 "Time": "1677-09-21T05:44:23.145224192+05:31"

**Comment by sixdouglas** [comment]
Hi,
Thank you for the issue. But I think this is not a real issue. In fact, on May the 17th, 2020 there were no night at this position. 
You can check it here : https://www.timeanddate.com/sun/@55.007379,82.956132, if you slide the date left to the 17th, you will see at the left end of the table below the grey and bleu drawing the sentence: "Not for this day".

<img width="1222" alt="Screenshot 2020-05-23 at 08 52 50" src="https://user-images.githubusercontent.com/3200319/82723967-e78c0580-9cd2-11ea-9839-b2b31f42bc8c.png">

But I agree with you, if there are no night, then there should be no Time returned. I think about returning [sql.NullTime](https://golang.org/pkg/database/sql/#NullTime).
Would it be ok for you?

**Comment by sixdouglas** [comment]
No answers for over 2 years
