### ISSUE TITLE
Moon Illumination values are not exported

### ISSUE THREAD

**Issue by josebiro** [sixdouglas/suncalc#7]
https://github.com/sixdouglas/suncalc/blob/f30ff7e4f3586cbc35044feec6f395bd9d459d52/suncalc.go#L256

This leads to them being unusable:
```
moonIllum.fraction undefined (cannot refer to unexported field or method fraction)
```

**Comment by sixdouglas** [comment]
You're right, my mistake.
Your PR has been merged.
